url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/kube-prometheus-stack
commit: 5c8e31ae6cb6e355900e2cbbd5cbceaec0c85821
packageVersion: 04
releaseCandidateVersion: 09
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: crd-manifest
      addCRDValidationToMainChart: true
