url:  https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-11.0.0/kube-prometheus-stack-11.0.0.tgz
packageVersion: 00
generateCRDChart:
  enabled: true
  assumeOwnershipOfCRDs: true
