url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/kube-prometheus-stack
commit: 3ab7f9b04e1ab5abd6c0b35268368422436ae3a6
packageVersion: 01
releaseCandidateVersion: 00
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: crd-manifest
      addCRDValidationToMainChart: true
