template: staging

sync:
- url: https://github.com/aiyengar/charts.git
  branch: test-drop-rc
validate:
- url: https://github.com/rancher/charts.git
  branch: main-alt
  dropReleaseCandidates: true
helmRepo:
  cname: charts.rancher.io