apiVersion: v1
version: 0.1.0
appVersion: 0.0.4
annotations:
  catalog.rancher.io/certified: rancher
  catalog.rancher.io/namespace: cattle-monitoring-system
  catalog.rancher.io/release-name: rancher-windows-exporter
  catalog.cattle.io/os: windows
description: Sets up monitoring metrics from Windows nodes via Prometheus windows-exporter
name: rancher-windows-exporter
maintainers:
- name: aiyengar2
  email: arvind.iyengar@rancher.com
type: application
