url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/prometheus-node-exporter
commit: 78d1219306eaca5be1d8bab84445d0489e073840
packageVersion: 01
releaseCandidateVersion: 00
