url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/prometheus-node-exporter
commit: 99f3c91249dfd7f846760c73054987a2b3ae244e
packageVersion: 01
releaseCandidateVersion: 00