# Default values for ${name}-crd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  cattle:
    systemDefaultRegistry: ""

image:
  repository: rancher/rancher-agent
  tag: v2.4-head
