# Default values for rancher-windows-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Configuration

global:
  cattle:
    systemDefaultRegistry: ""

prefixPath: c:\\

## Contains one or more configurations for the wins server to be applied across all of the nodes based on the nodeSelector and tolerations provided
##
winsConfigs:
- name: default
  image:
    # TODO(aiyengar2): replace with an image that just contains wins
    repository: rancher/wmi_exporter-package
    tag: v0.0.4
  config: |
    debug: false
    listen: rancher_wins
    proxy: rancher_wins_proxy
    white_list: 
      process_paths:
      - {{ .Values.prefixPath }}etc\windows-exporter\windows-exporter.exe
      - {{ .Values.prefixPath }}etc\wmi-exporter\wmi-exporter.exe
      - {{ .Values.prefixPath }}etc\kubernetes\bin\kube-proxy.exe
      - {{ .Values.prefixPath }}etc\kubernetes\bin\kubelet.exe
      - {{ .Values.prefixPath }}etc\nginx\nginx.exe
      - {{ .Values.prefixPath }}opt\bin\flanneld.exe
      proxy_ports:
      - 9796
    upgrade: 
      mode: watching
      watching_path: {{ .Values.prefixPath }}etc\rancher\wins\wins.exe
  # By default, `kubernetes.io/os: windows` or `beta.kubernetes.io/os: windows` will be included
  nodeSelector: {}
  # If provided, these tolerations will be used. Otherwise, it defaults to `[ {operator: Exists} ]`
  tolerations: []
